#!/usr/bin/env python3.3

import sys, os

path = ""
names = ""
lsOnly = False
for arg in sys.argv[1:]:
    if (arg == "-l"):
        lsOnly = True
        continue
    if (arg.startswith('/')
            or arg.startswith('./')
            or arg.startswith('~/')
            and os.path.exists(arg)):
        path += arg + " "
        continue
    if names:
        names += "-o "
    names += "-name \"*.%s\" " % arg
if not path:
    path = "."

if lsOnly:
    find = "find %s %s" %(path, names)
else:
    find = "find %s %s | xargs wc -l | sort -k 2" %(path, names)
    print(find)

os.system(find)
