#!/usr/bin/env python3

import sys, os

path = ""
names = ""
lsOnly = False
for arg in sys.argv[1:]:
    if (arg == "-l"):
        lsOnly = True
        continue
    if (arg.startswith('/')
            or arg.startswith('./')
            or arg.startswith('~/')
            and os.path.exists(arg)):
        path += arg + " "
        continue
    if names:
        names += "-o "
    names += "-name \"*.{}\" ".format(arg)
if not path:
    path = "./"

if lsOnly:
    find = "find {} {} -type f ".format(path, names)
else:
    find = "find {} {} -type f | xargs wc -l | sort -k 2".format(path, names)
    print(find)

os.system(find)
