#!/usr/bin/env python3.2

import sys, os

path = ""
names = ""
for arg in sys.argv[1:]:
    if (arg.startswith('/')
            or arg.startswith('./')
            or arg.startswith('~/')
            and os.path.exists(arg)):
        path += arg + " "
        continue
    if names:
        names += "-o "
    names += "-name \"*.%s\" " % arg
if not path:
    path = "."

find = "find %s %s | xargs wc -l | sort -k 2" %(path, names)
print(find)
os.system(find)
