#!/usr/bin/env python3.3
import sys
import os

if len(sys.argv) < 2:
    print("need a list of file paths!")
    sys.exit(-1)

pathList = sys.argv[1]
if not os.path.isfile(pathList):
    print("bad file: " + pathList)
    sys.exit(-2)

for path in open(pathList, mode='r', encoding='utf-8'):
    path = path.strip('\n')
    if os.path.isfile(path):
        print("- " + path)
        os.remove(path)
        
    path = os.path.dirname(path)
    
    while os.path.isdir(path) and not os.listdir(path):
        print("* " + path)
        os.rmdir(path)
        path = os.path.dirname(path)
